### ISSUE TITLE
Review Ticket - Week 1

### ISSUE THREAD

**Issue by ghost** [Archkitten/m22p1-weenies#20]
- Design Links: [PBL Journal w/ brainstorm](https://docs.google.com/document/d/1j3QMC7svdLn_iCbPPmVI2BF0OptxyuLwDC4ISRmdEwo/edit?usp=sharing), [Wiki Home](https://github.com/Archkitten/m22p1-weenies/wiki)
- Technicals: [10-12 Key Ideas](https://github.com/Archkitten/m22p1-weenies/wiki/10-to-12-Key-Ideas)
- Github: [Management Plan](https://github.com/Archkitten/m22p1-weenies/wiki/Management-Plan)
We are in the process of creating branches for each group member to push through 

- Deployment: [Comprehensive Deployment Guide w/ link](https://github.com/Archkitten/m22p1-weenies/wiki/Weenies-Deployment-Guide)
- Scrum Board: [Full Scrum Board with future + in progress ideas](https://github.com/Archkitten/m22p1-weenies/projects/1)

**Comment by jm1021** [comment]
Weenies - Sam 4.8/5
* Basic overview in Wikii 1/1
* Nice on 10 ideas 1/1
* Github done 1/1
* Deployment 1/1
* Scrum Board, Backup plannings .8/1

-.2 for no crossover review. 4.6/5
